server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/just_tech_news_java_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ENC(mH34+E3WlgzOfWvrrL9jxg==)
    password: ENC(0v712WIda8yiRD8rF/UVpvzSXmCYiUxv)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    # Spring Session Variables
    session:
      store-type: jdbc
      jdbc:
        initialize-schema: always
      timeout: 600
    h2:
      console:
        enabled: true
